import React from "react";

function main() {
    return (
        <div>
            <h1>
                <b>This is first main</b>
            </h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>This is main</h1>
            <h1>
                <b>This is last main</b>
            </h1>
        </div>
    );
}

export default main;
